### ISSUE TITLE
Python 3.9 error

### ISSUE THREAD

**Issue by ajikmr** [google-deepmind/graphcast#2]
Though code works fine with python 3.10, python 3.9 throws error.

Traceback (most recent call last):
  File "/xxxxxxxgraphcast/graphcast_example.py", line 44, in <module>
    ckpt=checkpoint.load(f, graphcast.CheckPoint)
  File "/xxxxxxxgraphcast/graphcast/checkpoint.py", line 54, in load
    return _convert_types(typ, _unflatten(np.load(source)))
  File "/xxxxxxxgraphcast/graphcast/checkpoint.py", line 117, in _convert_types
    if isinstance(f.type, (types.UnionType, type(Optional[int]))):
AttributeError: module 'types' has no attribute 'UnionType'

OS: Ubuntu 20.04.6
Python: 3.9.17
jax: 0.4.14

**Comment by alvarosg** [comment]
Thank you for flagging this. In principle we support python 3.10 and above. We have updated `setup.py` to indicate this.

Thanks again!
